### ISSUE TITLE
Request for Prebuilt boot.img only with LXC and Without KernelSU

### ISSUE THREAD

**Issue by DataEraserC** [kde-yyds/lindroid-roms#1]
Hi,

I'm currently testing the Lindroid Android distribution using DSU sideloader. To ensure a seamless transition from my existing Apatch kernel, I need a prebuilt `boot.img` with LXC enabled and KernelSU disabled.

Could you please provide such a build for testing purposes?

Thank you for your help!

Best,DataEraserC

**Comment by kde-yyds** [comment]
I will build one

**Comment by kde-yyds** [comment]
also android12-5.10?

**Comment by kde-yyds** [comment]
You also have a mondrian?

**Comment by kde-yyds** [comment]
![screenshot](https://github.com/user-attachments/assets/b1f27a7e-422b-42c8-885e-ab4a589b87e2)
now buiilding

**Comment by kde-yyds** [comment]
https://github.com/kde-yyds/lindroid-roms/releases/download/1/android12-5.10-boot-lxc-noksu.img

**Comment by DataEraserC** [comment]
thanks very much!

**Comment by DataEraserC** [comment]
> You also have a mondrian?

yes

**Comment by kde-yyds** [comment]
don't forget to disable avb 2.0 before installing dsu

**Comment by DataEraserC** [comment]
I successfully booted lindroid, and kde is working normally. By flashing the kernel you provided and loading the ROM you compiled through the dsu sideloader, I am extremely grateful.

**Comment by kde-yyds** [comment]
> I successfully booted lindroid, and kde is working normally. By flashing the kernel you provided and loading the ROM you compiled through the dsu sideloader, I am extremely grateful.

i'm also happy to see it working on your device

**Comment by DataEraserC** [comment]
Thank you very much indeed, and I was wondering if it's possible to directly patch the system (using methods like Xposed for injection or direct patching) + compile a custom kernel to achieve porting lindroid onto a non-open source system.

**Comment by kde-yyds** [comment]
> Thank you very much indeed, and I was wondering if it's possible to directly patch the system (using methods like Xposed for injection or direct patching) + compile a custom kernel to achieve porting lindroid onto a non-open source system.

i think it's possible. there are some libdroid modules in the telegram group. but they does not work on miui or hyperos. the android14 one makes hyperos not booting, android13 one (packed by me) cause touch offset on miui14, and lindroid crashes.
